/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prj.morcego.interfaces;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import prj.morcego.serial.Serial;
import prj.morcego.grafico.PlanoCartesiano;
import prj.morcego.grafico.Ponto;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ricardo
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    int escalaX;
    int escalaY;
    String serialPort = null;

    public Principal() {
        initComponents();
        progressBar.setVisible(false);
        grauTextField.setText("" + anguloInicial);

        centro_x = jPanel1.getWidth() / 2;
        centro_y = jPanel1.getHeight() / 2;

        escalaX = centro_x;
        escalaY = centro_y;
        textCentoX.setText("" + centro_x);
        textCentroY.setText("" + centro_y);

        sobeButton.setOpaque(false);
        sobeButton.setContentAreaFilled(false);
        sobeButton.setBorderPainted(false);
        esquerdaButton.setOpaque(false);
        esquerdaButton.setContentAreaFilled(false);
        esquerdaButton.setBorderPainted(false);
        direitaButton.setOpaque(false);
        direitaButton.setContentAreaFilled(false);
        direitaButton.setBorderPainted(false);
        desceButton.setOpaque(false);
        desceButton.setContentAreaFilled(false);
        desceButton.setBorderPainted(false);
        menos10.setOpaque(false);
        menos10.setContentAreaFilled(false);
        menos10.setBorderPainted(false);
        mais10.setOpaque(false);
        mais10.setContentAreaFilled(false);
        mais10.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        graficoPanel = new javax.swing.JPanel();
        jPanel1 = new Painel();
        statusLabel = new javax.swing.JLabel();
        configPanel = new javax.swing.JPanel();
        iniciarButton = new javax.swing.JToggleButton();
        pararButton = new javax.swing.JToggleButton();
        jButton2 = new javax.swing.JButton();
        mais10 = new javax.swing.JButton();
        menos10 = new javax.swing.JButton();
        sobeButton = new javax.swing.JButton();
        esquerdaButton = new javax.swing.JButton();
        direitaButton = new javax.swing.JButton();
        desceButton = new javax.swing.JButton();
        textCentoX = new javax.swing.JTextField();
        xLavel = new javax.swing.JLabel();
        yLabel = new javax.swing.JLabel();
        textCentroY = new javax.swing.JTextField();
        grauTextField = new javax.swing.JTextField();
        grausLabel = new javax.swing.JLabel();
        serialComboBox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mi_limpar = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        mi_sair = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ProjetoMorcego");
        setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        setForeground(java.awt.Color.lightGray);

        jLabel1.setFont(new java.awt.Font("Droid Serif", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(4, 2, 2));
        jLabel1.setText("Projeto Morcego");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prj/morcego/img/morcego-icone.png"))); // NOI18N

        graficoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Grafico", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Abyssinica SIL", 0, 10), java.awt.Color.black)); // NOI18N
        graficoPanel.setToolTipText("");

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 576, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout graficoPanelLayout = new javax.swing.GroupLayout(graficoPanel);
        graficoPanel.setLayout(graficoPanelLayout);
        graficoPanelLayout.setHorizontalGroup(
            graficoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(graficoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(graficoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(graficoPanelLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, graficoPanelLayout.createSequentialGroup()
                        .addComponent(statusLabel)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        graficoPanelLayout.setVerticalGroup(
            graficoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(graficoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(statusLabel)
                .addGap(6, 6, 6))
        );

        configPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Configuraçoes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Abyssinica SIL", 0, 10), java.awt.Color.black)); // NOI18N

        iniciarButton.setText("Ler");
        iniciarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iniciarButtonMouseClicked(evt);
            }
        });
        iniciarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarButtonActionPerformed(evt);
            }
        });

        pararButton.setText("Parar");
        pararButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pararButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Limpar Tela");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        mais10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prj/morcego/img/rotacionar1.png"))); // NOI18N
        mais10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mais10ActionPerformed(evt);
            }
        });

        menos10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prj/morcego/img/rotacionar2.png"))); // NOI18N
        menos10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menos10ActionPerformed(evt);
            }
        });

        sobeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prj/morcego/img/seta-cima.png"))); // NOI18N
        sobeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sobeButtonActionPerformed(evt);
            }
        });

        esquerdaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prj/morcego/img/seta-esquerda.png"))); // NOI18N
        esquerdaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esquerdaButtonActionPerformed(evt);
            }
        });

        direitaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prj/morcego/img/seta-direita.png"))); // NOI18N
        direitaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direitaButtonActionPerformed(evt);
            }
        });

        desceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prj/morcego/img/seta-baixo.png"))); // NOI18N
        desceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desceButtonActionPerformed(evt);
            }
        });

        textCentoX.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textCentoX.setText(" ");

        xLavel.setText("0x");

        yLabel.setText("0y");

        textCentroY.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textCentroY.setText(" ");
        textCentroY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCentroYActionPerformed(evt);
            }
        });

        grauTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        grauTextField.setText(" ");
        grauTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grauTextFieldActionPerformed(evt);
            }
        });

        grausLabel.setText("º");

        serialComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "COM11", "COM10", "COM3", "dev/ttyUSB0", "dev/ttyUSB1", "Bluetooth" }));
        serialComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serialComboBoxActionPerformed(evt);
            }
        });

        jLabel6.setText("USB");

        javax.swing.GroupLayout configPanelLayout = new javax.swing.GroupLayout(configPanel);
        configPanel.setLayout(configPanelLayout);
        configPanelLayout.setHorizontalGroup(
            configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, configPanelLayout.createSequentialGroup()
                .addGroup(configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(configPanelLayout.createSequentialGroup()
                            .addGap(48, 48, 48)
                            .addComponent(sobeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(configPanelLayout.createSequentialGroup()
                            .addComponent(esquerdaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(direitaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(configPanelLayout.createSequentialGroup()
                            .addGap(46, 46, 46)
                            .addComponent(desceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(pararButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(configPanelLayout.createSequentialGroup()
                            .addComponent(mais10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(menos10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(iniciarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, configPanelLayout.createSequentialGroup()
                        .addGroup(configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(grausLabel)
                            .addComponent(yLabel)
                            .addComponent(xLavel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(configPanelLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(textCentoX, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(grauTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textCentroY, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(configPanelLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(serialComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6))
        );
        configPanelLayout.setVerticalGroup(
            configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(configPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iniciarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pararButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mais10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menos10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sobeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(esquerdaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(direitaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serialComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(0, 0, 0)
                .addGroup(configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xLavel)
                    .addComponent(textCentoX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yLabel)
                    .addComponent(textCentroY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grausLabel)
                    .addComponent(grauTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(22, 20, 9));

        jMenu1.setText("Iniciar");

        mi_limpar.setText("Limpar Tela");
        mi_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_limparActionPerformed(evt);
            }
        });
        jMenu1.add(mi_limpar);

        jMenuItem1.setText("Salvar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        mi_sair.setText("Sair");
        mi_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_sairActionPerformed(evt);
            }
        });
        jMenu1.add(mi_sair);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(configPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(graficoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(0, 201, Short.MAX_VALUE))
                    .addComponent(progressBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(configPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(graficoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        graficoPanel.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static int centro_x = 0;
    public static int centro_y = 0;

    private ArrayList<Ponto> pontosLidos = new ArrayList<Ponto>();
    Serial serial;
    private int anguloInicial = 0;
    //ControlePorta ardCon = new ControlePorta("COM3",9600); /*Windows*/

    private void setSerialPort() {
        if (serialComboBox.getSelectedIndex() == 0) {
            serialPort = "dev/ttyUSB0";
        } else if (serialComboBox.getSelectedIndex() == 1) {
            serialPort = "dev/ttyUSB1";
        } else if (serialComboBox.getSelectedIndex() == 2) {
            serialPort = "COM3";
        } else if (serialComboBox.getSelectedIndex() == 3) {
            serialPort = "COM3";
        }
    }

    /**
     *
     * classe interna para tratamento de eventos de bot�es e itens de menu
     */
    private class Al_Eventos implements ActionListener {

        public void actionPerformed(ActionEvent event) {
            if (event.getSource() == mi_sair) {
                System.exit(0);
            }
        }
    }

    private void mi_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_sairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mi_sairActionPerformed

    private void mi_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_limparActionPerformed
        this.jPanel1.repaint();
    }//GEN-LAST:event_mi_limparActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try {
            ((Painel) Principal.this.jPanel1).salvarImagem("/home/ricardo/", centro_x * 2, centro_y * 2);
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void serialComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serialComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serialComboBoxActionPerformed

    private void desceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desceButtonActionPerformed
        centro_y += 10;
        textCentroY.setText("" + centro_y);
    }//GEN-LAST:event_desceButtonActionPerformed

    private void direitaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direitaButtonActionPerformed
        centro_x += 10;
        textCentoX.setText("" + centro_x);
    }//GEN-LAST:event_direitaButtonActionPerformed

    private void esquerdaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esquerdaButtonActionPerformed
        centro_x -= 10;
        textCentoX.setText("" + centro_x);
    }//GEN-LAST:event_esquerdaButtonActionPerformed

    private void sobeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sobeButtonActionPerformed
        centro_y -= 10;
        textCentroY.setText("" + centro_y);
    }//GEN-LAST:event_sobeButtonActionPerformed

    private void menos10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menos10ActionPerformed
        anguloInicial -= 10;
        grauTextField.setText("" + anguloInicial);
    }//GEN-LAST:event_menos10ActionPerformed

    private void mais10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mais10ActionPerformed
        anguloInicial += 10;
        grauTextField.setText("" + anguloInicial);
    }//GEN-LAST:event_mais10ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.jPanel1.repaint();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void pararButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pararButtonActionPerformed
        pararButton.setSelected(false);
        serial.enviaDados(2);
        serial.close();
        progressBar.setVisible(false);
    }//GEN-LAST:event_pararButtonActionPerformed

    String simula_ang[] = {"0", "10","20","30","40","50", "60","70","80","90","100","110","120","130","140","150","160","170","180"};
    String simila_dist[] = {"6.0","6.3","6.6","7.3","7.9","9.6","10.3","9.7","9.3","9.0","9.0","9.3","9.7","10.3","9.6","7.9","7.3","6.6","6.3","6.0"};
    String q_simila_dist[] = {"6.0","6.3","6.6","7.3","7.9","7.5","6.7","8.5","9.3","9.0","9.0","9.3","9.7","10.3","9.6","7.9","7.3","6.6","6.3","6.0"};
    String c_simila_dist[] = {"6.0","6.3","6.6","7.3","7.9","7.8","7.8","8.3","9.3","9.0","9.0","9.3","9.7","10.3","9.6","7.9","7.3","6.6","6.3","6.0"};
    
    private void iniciarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarButtonActionPerformed
        setSerialPort();
        System.out.println(serialPort);

        try {
            ((Painel) Principal.this.jPanel1).desenhaRobo((int) centro_x, (int) centro_y);
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        iniciarButton.setSelected(false);
        //this.jPanel1.repaint();
        try {
            serial = new Serial();
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        serial.initialize();/*incializa a leitora da porta serial*/

        Runnable myThread = new Runnable() {

            @Override
            public void run() {

                //Cria um plano cartesiano
                PlanoCartesiano plano = new PlanoCartesiano();
                setIniciaLeitura();
                /*serial.enviaDados(1); //envia 1 para acender o led
                serial.enviaDados(3); //envia 3 para fazer uma eitura
                /*for (int i = 0; i < 22; i++) {
                    serial.enviaDados(1); //envia 1 para acender o led
                    serial.enviaDados(3); //envia 3 para fazer uma eitura
                    try {
                        Thread.sleep(500);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }*/
                /*setFinalizaLeitura();

                serial.close(); /*para de ler a serial*/
                
                for (int i = 0; i < simula_ang.length; i++) {
                    Ponto pont = new Ponto();
                    pont.setAngulo(Integer.parseInt(simula_ang[i]));
                    pont.setDist(Double.parseDouble(simila_dist[i])); 
                    pontosLidos.add(pont);
                }
                setFinalizaLeitura();

                //pontosLidos = serial.getPontos_lidos();/*salva os pontos, um ponto é composto por uma distância e por um ângulo*/

                /*atualiza dos dados mostrados*/
                textCentoX.setText("" + centro_x);
                textCentroY.setText("" + centro_y);

                plano.setEixo_x(centro_x);
                plano.setEixo_y(centro_y);
                System.out.println("Quantidade de pontos lidos " + pontosLidos.size());
                for (int i = 0; i < pontosLidos.size(); i++) {
                    pontosLidos.get(i).setAnguloInicial(anguloInicial);
                    pontosLidos.get(i).decompoePonto(escalaX / 20, escalaY / 20);
                    System.out.println(pontosLidos.get(i).getX() + " " + pontosLidos.get(i).getY());
                    //adiciona ao plano o ponto
                    plano.addPonto(pontosLidos.get(i));
                }
                //desenhar os pontos
                ((Painel) Principal.this.jPanel1).desenharPlano(plano);

            }

            private void setIniciaLeitura() {
                progressBar.setVisible(true);
                progressBar.setIndeterminate(true);
                statusLabel.setText("Realizando leitura ...");
            }

            private void setFinalizaLeitura() {
                progressBar.setVisible(false);
                progressBar.setIndeterminate(false);
                statusLabel.setText("");
            }

        };

        Thread t = new Thread(myThread);
        t.start();
    }//GEN-LAST:event_iniciarButtonActionPerformed

    private void iniciarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciarButtonMouseClicked

    }//GEN-LAST:event_iniciarButtonMouseClicked

    private void textCentroYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCentroYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCentroYActionPerformed

    private void grauTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grauTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_grauTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel configPanel;
    private javax.swing.JButton desceButton;
    private javax.swing.JButton direitaButton;
    private javax.swing.JButton esquerdaButton;
    private javax.swing.JPanel graficoPanel;
    private javax.swing.JTextField grauTextField;
    private javax.swing.JLabel grausLabel;
    private javax.swing.JToggleButton iniciarButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mais10;
    private javax.swing.JButton menos10;
    private javax.swing.JMenuItem mi_limpar;
    private javax.swing.JMenuItem mi_sair;
    private javax.swing.JToggleButton pararButton;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JComboBox serialComboBox;
    private javax.swing.JButton sobeButton;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JTextField textCentoX;
    private javax.swing.JTextField textCentroY;
    private javax.swing.JLabel xLavel;
    private javax.swing.JLabel yLabel;
    // End of variables declaration//GEN-END:variables
}
